package crabster.rudakov.sberschoollesson26hwk

object Constants {

    const val ACTION_START_SERVICE = "ACTION_START_SERVICE"
    const val ACTION_STOP_SERVICE = "ACTION_STOP_SERVICE"
    const val ACTION_ACTIVITY_CHRONOMETER = "ACTION_ACTIVITY_CHRONOMETER"
    const val ACTION_START = "ACTION_START"
    const val ACTION_PAUSE = "ACTION_PAUSE"
    const val ACTION_STOP = "ACTION_STOP"
    const val LOG_ON_CREATE_TAG = "SERVICE"
    const val LOG_ON_CREATE_MESSAGE = "SERVICE IS WORKING"
    const val LOG_BROADCAST_RECEIVER_TAG = "BROADCAST RECEIVER"
    const val LOG_BROADCAST_RECEIVER_MESSAGE = "BROADCAST RECEIVER IS LAUNCHED"
    const val INTENT_CHRONOMETER_TIME_KEY = "ACTIVITY_CHRONOMETER_TIME"
    const val INTENT_CHRONOMETER_COMMAND_KEY = "ACTIVITY_CHRONOMETER_COMMAND"
    const val INTENT_CHRONOMETER_COMMAND_START = "START"
    const val INTENT_CHRONOMETER_COMMAND_PAUSE = "PAUSE"
    const val INTENT_CHRONOMETER_COMMAND_STOP = "STOP"
    const val NOTIFICATION_ID = 1
    const val CHANNEL_NAME = "NOTIFICATION SERVICE"
    const val CHANNEL_DESCRIPTION = "TIMER & BATTERY PROPERTIES"
    const val CHANNEL_ID = "1"

}